from langgraph.types import Send
from State.banking_state import BankingState
from Utils.Logger import get_logger

logger = get_logger("DISTRIBUTE TAKS EDGE")

def distribute_tasks(state: BankingState):
    """
    Reads the list of tasks generated by the orchestrator and spins up 
    a parallel worker node for each one.
    """
    tasks = state.get("tasks", [])
    
    if not tasks:
        logger.warning("No tasks found to distribute. Routing straight to aggregator.")
        return []

    logger.info(f"🔀 DISTRIBUTING: Spinning up {len(tasks)} parallel workers.")

    send_commands = []
    for task in tasks:
        task_type = task.get("type", "general")

        if task_type == "account":
            send_commands.append(Send("account_agent", {"tasks": task}))
        elif task_type == "transaction":
            # (Future) Route to transaction agent
            send_commands.append(Send("transaction_agent", {"tasks": task}))
        elif task_type == "knowledge": 
            send_commands.append(Send("knowledge_agent", {"task": task}))
        else:
            # Fallback to the generic worker node
            send_commands.append(Send("worker_node", {"tasks": task}))

    return send_commands