import sqlite3
import streamlit as st
import uuid
import asyncio
import os
from dotenv import load_dotenv

from mcp.client.sse import sse_client
from mcp.client.session import ClientSession
from langchain_mcp_adapters.tools import load_mcp_tools
from langchain_core.messages import AIMessage, HumanMessage
from langgraph.checkpoint.sqlite import SqliteSaver
from langgraph.checkpoint.sqlite.aio import AsyncSqliteSaver

# Imports from your project
from Utils.HistoryLoaders import load_chat_history
from main import build_graph

# Load environment variables (for LangSmith)
load_dotenv()

# -----------------------------------------------------------------------------
# Import your SQLite LTM Store 
# -----------------------------------------------------------------------------
try:
    from Utils.database_manager import ltm_store
except ImportError:
    try:
        from main import ltm_store  
    except ImportError:
        ltm_store = None
    if ltm_store is None:
        st.warning("⚠️ LTM Store could not be imported. Please verify your database manager file.")

MCP_SERVER_URL = "http://localhost:8000/mcp/sse"

# -----------------------------------------------------------------------------
# 1. Page Configuration & Session Setup
# -----------------------------------------------------------------------------
st.set_page_config(page_title="Banking Assistant", page_icon="🏦", layout="centered")
st.title("🏦 Secure Banking Agent")

# Initialize persistent SQLite Checkpointer for UI State reads
if "checkpointer" not in st.session_state:
    sqlite_conn = sqlite3.connect("banking_checkpoints.db", check_same_thread=False)
    st.session_state.checkpointer = SqliteSaver(sqlite_conn)

if "thread_id" not in st.session_state:
    st.session_state.thread_id = "user_thread_123" 
    st.session_state.user_id = "rathan_123"

thread_config = {
    "configurable": {
        "thread_id": st.session_state.thread_id,
        "user_id": st.session_state.user_id
    }
}

# Create a synchronous app instance that always exists just for reading state
temp_app = build_graph(
    all_mcp_tools=[], 
    checkpointer=st.session_state.checkpointer,
    ltm_store=ltm_store
)

# Initialize UI chat messages history & Load Past History (STM)
if "messages" not in st.session_state:
    with st.spinner("Loading previous conversation..."):
        past_messages = load_chat_history(temp_app, st.session_state.thread_id)
        st.session_state.messages = past_messages if past_messages else []


# -----------------------------------------------------------------------------
# 2. Async Graph Execution Helper (With Streaming & Dual Checkpointing)
# -----------------------------------------------------------------------------
async def run_and_stream_turn(inputs, thread_config, ui_placeholder=None):
    """Establishes MCP connection, runs graph, and streams specific node outputs."""
    async with sse_client(MCP_SERVER_URL) as (read_stream, write_stream):
        async with ClientSession(read_stream, write_stream) as session:
            await session.initialize()
            mcp_tools = await load_mcp_tools(session)
            
            # Open an async checkpointer pointing to the exact same database file
            async with AsyncSqliteSaver.from_conn_string("banking_checkpoints.db") as async_checkpointer:
                
                app = build_graph(
                    all_mcp_tools=mcp_tools, 
                    checkpointer=async_checkpointer, 
                    ltm_store=ltm_store
                )
                
                full_response = ""
                
                # Listen to graph execution
                stream_target = app.astream_events(inputs, config=thread_config, version="v2")
                
                async for event in stream_target:
                    kind = event["event"]
                    
                    if kind == "on_chat_model_stream":
                        node_name = event["metadata"].get("langgraph_node")
                        
                        # Only stream tokens generated by the aggregator
                        if node_name == "aggregator":
                            chunk = event["data"]["chunk"]
                            if chunk.content and isinstance(chunk.content, str):
                                full_response += chunk.content
                                if ui_placeholder:
                                    ui_placeholder.markdown(full_response + " ▌")
                
                # Remove cursor when finished
                if ui_placeholder and full_response:
                    ui_placeholder.markdown(full_response)
                
                return app, full_response

def execute_turn_stream(inputs, placeholder=None):
    """Synchronous wrapper for Streamlit"""
    return asyncio.run(run_and_stream_turn(inputs, thread_config, placeholder))

# -----------------------------------------------------------------------------
# 3. Sidebar Controls
# -----------------------------------------------------------------------------
with st.sidebar:
    st.header("Session Settings")
    st.caption(f"Thread ID:\n`{st.session_state.thread_id}`")
    
    if st.button("🔄 Clear Chat / New Session", use_container_width=True):
        st.session_state.thread_id = str(uuid.uuid4())
        st.session_state.messages = []
        st.rerun()

# -----------------------------------------------------------------------------
# 4. Render Conversation History
# -----------------------------------------------------------------------------
for msg in st.session_state.messages:
    if hasattr(msg, 'type'):
        role = "user" if msg.type == "human" else "assistant"
        content = msg.content
    elif isinstance(msg, dict):
        role = msg.get("role", "assistant")
        content = msg.get("content", "")
    else:
        continue
        
    with st.chat_message(role):
        st.markdown(content)

# -----------------------------------------------------------------------------
# 5. Check State for Interrupts (Human-In-The-Loop Approval)
# -----------------------------------------------------------------------------
try:
    temp_state = st.session_state.checkpointer.get(thread_config)
    next_node = temp_state.get("next", ()) if temp_state else ()
except Exception as e:
    print(f"Graph State Check Error: {e}") 
    next_node = ()

if next_node and "sensitive_tools_node" in next_node:
    st.warning("⚠️ **Action Required:** This transaction requires human authorization.")
    
    col1, col2 = st.columns(2)
    with col1:
        if st.button("✅ Approve Transfer", type="primary", use_container_width=True):
            stream_placeholder = st.empty()
            
            _, final_answer = execute_turn_stream(inputs=None, placeholder=stream_placeholder)
            
            if not final_answer:
                # Fallback if stream was empty
                current_state = temp_app.get_state(thread_config)
                final_answer = current_state.values.get("generation", "Transaction completed successfully.")
                stream_placeholder.markdown(final_answer)
                
            st.session_state.messages.append(AIMessage(content=final_answer))
            st.rerun()
                
    with col2:
        if st.button("❌ Reject / Cancel", use_container_width=True):
            st.session_state.messages.append(AIMessage(content="Transaction was cancelled by user."))
            st.session_state.thread_id = str(uuid.uuid4())
            st.rerun()

# -----------------------------------------------------------------------------
# 6. Standard User Chat Input
# -----------------------------------------------------------------------------
else:
    if prompt := st.chat_input("Ask about your accounts, policies, or initiate transfers..."):
        
        st.session_state.messages.append(HumanMessage(content=prompt))
        with st.chat_message("user"):
            st.markdown(prompt)

        input_state = {
            "question": prompt,
            "worker_responses": []
        }

        with st.chat_message("assistant"):
            stream_placeholder = st.empty()
            stream_placeholder.markdown("*(Analyzing request and routing...)*")
            
            try:
                _, final_answer = execute_turn_stream(input_state, stream_placeholder)
                
                # Fetch state using the synchronous app
                current_state = temp_app.get_state(thread_config)
                
                # Prevent UI freeze if the stream was empty
                if not final_answer:
                    final_answer = current_state.values.get("generation", "I'm sorry, I was unable to process your request.")
                    stream_placeholder.markdown(final_answer)

                if current_state.next and "sensitive_tools_node" in current_state.next:
                    st.session_state.messages.append(
                        AIMessage(content="⚠️ Transfer pending approval. Please review the details above.")
                    )
                else:
                    st.session_state.messages.append(AIMessage(content=final_answer))
                
                st.rerun()

            except Exception as e:
                import traceback
                traceback.print_exc() 
                st.error("I'm sorry, an internal system error occurred while processing your request.")